# Generated by Django 5.1 on 2024-09-15 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIReview', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
